<?php

// ============================================================================
// Lote-piloto: ENEM 2024 — 2º dia — Caderno 5 (Amarelo). Questões 91 a 180.
//
// Fonte das respostas: gabarito oficial (2024_GB_impresso_D2_CD5). Q102 anulada.
// Fonte do texto: transcrição fiel da prova oficial (2024_PV_impresso_D2_CD5),
// usada como conteúdo de indexação/acessibilidade e visual PROVISÓRIO até os
// recortes oficiais das páginas serem gerados (ver tools/import-enem.php). Onde
// há figura/gráfico/tabela, o texto traz o marcador [imagem oficial pendente].
//
// Campos por questão:
//   n, discipline, correct, status, content, competency, skill, confidence,
//   review, page (página impressa da prova), statement, alternatives[A..E]
//
// confidence: alta|media|baixa  ·  review: true marca revisão pedagógica humana.
// ============================================================================

$Q = function (array $a): array { return $a; };

return [
    'exam' => [
        'slug' => 'enem-2024-d2-c5-amarelo',
        'name' => 'ENEM 2024 — 2º dia — Caderno 5 (Amarelo)',
        'year' => 2024,
        'day' => 2,
        'booklet' => '5',
        'color' => 'amarelo',
        'source_label' => '2024_PV_impresso_D2_CD5 + gabarito oficial',
        'image_basename' => 'enem-2024-dia2-caderno5-amarelo',
    ],

    'questions' => [
        // ===================== Ciências da Natureza (91–135) =====================
        ['n' => 91, 'discipline' => 'Biologia', 'correct' => 'C', 'status' => 'ativa', 'content' => 'Moléculas, células e tecidos', 'competency' => 'CN-C8', 'skill' => 'CN-H15', 'confidence' => 'alta', 'review' => false, 'page' => 2,
            'statement' => 'Experimento com Amoeba proteus tratada com a droga citocalasina B (e grupo controle não tratado). O formato e o movimento das células tratadas foram comprometidos. Qual componente celular foi afetado pela droga? [imagem oficial pendente: esquema das amebas]',
            'alternatives' => ['A' => 'Vacúolos.', 'B' => 'Mitocôndrias.', 'C' => 'Microfilamentos.', 'D' => 'Material genético.', 'E' => 'Membrana plasmática.']],
        ['n' => 92, 'discipline' => 'Química', 'correct' => 'A', 'status' => 'ativa', 'content' => 'Materiais, propriedades e separação de misturas', 'competency' => 'CN-C7', 'skill' => 'CN-H24', 'confidence' => 'alta', 'review' => false, 'page' => 2,
            'statement' => 'Na produção de magnésio metálico a partir da água do mar, a reação Mg2+ (aq) + Ca(OH)2 (aq) → Mg(OH)2 (s) + Ca2+ (aq) gera uma mistura com hidróxido de magnésio pouco solúvel e íons Ca2+. O método adequado para separar o Mg(OH)2 dessa mistura é a',
            'alternatives' => ['A' => 'filtração.', 'B' => 'catação.', 'C' => 'destilação.', 'D' => 'dissolução.', 'E' => 'evaporação.']],
        ['n' => 93, 'discipline' => 'Biologia', 'correct' => 'E', 'status' => 'ativa', 'content' => 'Identidade dos seres vivos', 'competency' => 'CN-C4', 'skill' => 'CN-H14', 'confidence' => 'alta', 'review' => false, 'page' => 2,
            'statement' => 'Anfíbios anuros (Eleutherodactylus jahnstonei) trazidos do Caribe emitem som alto e estridente em São Paulo. Ao emitirem o som estridente, esses anfíbios',
            'alternatives' => ['A' => 'indicam que estão fora de seu hábitat natural.', 'B' => 'alertam para a presença de poluição urbana.', 'C' => 'sinalizam a existência de superpopulação.', 'D' => 'direcionam insetos para sua alimentação.', 'E' => 'atraem fêmeas para o acasalamento.']],
        ['n' => 94, 'discipline' => 'Química', 'correct' => 'D', 'status' => 'ativa', 'content' => 'Água, soluções e equilíbrio ácido-base', 'competency' => 'CN-C7', 'skill' => 'CN-H27', 'confidence' => 'alta', 'review' => false, 'page' => 2,
            'statement' => 'A hidroxiapatita do esmalte está em equilíbrio de desmineralização/mineralização (favorecida por H+). Considerando o pH de cremes dentais (I bicarbonato de sódio 9,5; II carbonato de cálcio 11,0; III citrato de potássio 7,7; IV dióxido de silício 6,9; V fosfato de cálcio 7,3), qual creme promove a maior desmineralização do esmalte? [imagem oficial pendente: equação e quadro de pH]',
            'alternatives' => ['A' => 'I', 'B' => 'II', 'C' => 'III', 'D' => 'IV', 'E' => 'V']],
        ['n' => 95, 'discipline' => 'Física', 'correct' => 'A', 'status' => 'ativa', 'content' => 'Calor e fenômenos térmicos', 'competency' => 'CN-C6', 'skill' => 'CN-H21', 'confidence' => 'alta', 'review' => false, 'page' => 3,
            'statement' => 'Tirinha: esquimós em um iglu usam uma geladeira para fazer gelo. Na tirinha, a geladeira é necessária para fazer gelo porque [imagem oficial pendente: tirinha]',
            'alternatives' => ['A' => 'a temperatura interna do iglu é maior que a de solidificação da água.', 'B' => 'a umidade dentro do iglu dificulta o processo de mudança de fase da água.', 'C' => 'o ar dentro do iglu é isolante térmico, dificultando a perda de calor pela água.', 'D' => 'a temperatura uniforme no interior do iglu impede as correntes de convecção.', 'E' => 'a pressão do ar no interior do iglu é baixa, dificultando a solidificação da água.']],
        ['n' => 96, 'discipline' => 'Química', 'correct' => 'A', 'status' => 'ativa', 'content' => 'Compostos de carbono (química orgânica)', 'competency' => 'CN-C7', 'skill' => 'CN-H24', 'confidence' => 'alta', 'review' => false, 'page' => 3,
            'statement' => 'Pesticidas naturais (compostos 1 e 2) atuam na defesa das plantas. Qual é a função orgânica correspondente ao grupo funcional comum presente nesses dois compostos? [imagem oficial pendente: estruturas dos compostos 1 e 2]',
            'alternatives' => ['A' => 'Ácido carboxílico.', 'B' => 'Cetona.', 'C' => 'Alceno.', 'D' => 'Álcool.', 'E' => 'Fenol.']],
        ['n' => 97, 'discipline' => 'Biologia', 'correct' => 'C', 'status' => 'ativa', 'content' => 'Identidade dos seres vivos', 'competency' => 'CN-C8', 'skill' => 'CN-H29', 'confidence' => 'media', 'review' => false, 'page' => 3,
            'statement' => 'Três gêneros bacterianos cultivados em tubos de ensaio apresentaram padrões distintos de distribuição das células. Em relação ao metabolismo energético, os microrganismos dos tubos 1, 2 e 3 são classificados, respectivamente, como [imagem oficial pendente: figura dos tubos]',
            'alternatives' => ['A' => 'anaeróbio facultativo, anaeróbio estrito e aeróbio estrito.', 'B' => 'anaeróbio facultativo, aeróbio estrito e anaeróbio estrito.', 'C' => 'aeróbio estrito, anaeróbio estrito e anaeróbio facultativo.', 'D' => 'anaeróbio estrito, aeróbio estrito e anaeróbio facultativo.', 'E' => 'aeróbio estrito, anaeróbio facultativo e anaeróbio estrito.']],
        ['n' => 98, 'discipline' => 'Física', 'correct' => 'C', 'status' => 'ativa', 'content' => 'Oscilações, ondas, óptica e radiação', 'competency' => 'CN-C6', 'skill' => 'CN-H22', 'confidence' => 'media', 'review' => true, 'page' => 4,
            'statement' => 'Placas de saída de emergência brilham no escuro (fosforescência amarelo-esverdeada) por conter sulfeto de zinco (ZnS) dopado. O aparecimento do brilho ocorre como consequência de [imagem oficial pendente: placa]',
            'alternatives' => ['A' => 'colisões interatômicas.', 'B' => 'coloração dos átomos.', 'C' => 'transições eletrônicas.', 'D' => 'reações nucleares.', 'E' => 'reflexão da luz.']],
        ['n' => 99, 'discipline' => 'Biologia', 'correct' => 'A', 'status' => 'ativa', 'content' => 'Qualidade de vida das populações humanas', 'competency' => 'CN-C8', 'skill' => 'CN-H30', 'confidence' => 'alta', 'review' => false, 'page' => 4,
            'statement' => 'Vacinas contra a covid-19 usam a proteína de superfície viral espícula (spike). Nessas vacinas, essa proteína viral induz a',
            'alternatives' => ['A' => 'produção de anticorpos específicos contra os vírus.', 'B' => 'imunidade passiva contra o desenvolvimento da doença.', 'C' => 'alteração genômica para formação da memória imunológica.', 'D' => 'neutralização direta dos vírus presentes na circulação sanguínea.', 'E' => 'modificação dos receptores de membrana específicos para o vírus.']],
        ['n' => 100, 'discipline' => 'Física', 'correct' => 'E', 'status' => 'ativa', 'content' => 'Fenômenos elétricos e magnéticos', 'competency' => 'CN-C6', 'skill' => 'CN-H21', 'confidence' => 'media', 'review' => true, 'page' => 4,
            'statement' => 'Duas barras com cargas opostas em óleo; farelo de milho revela as linhas de campo elétrico. Ao colocar um cilindro metálico oco entre as placas, qual esquema representa o formato das linhas de campo? [imagem oficial pendente: alternativas com figuras]',
            'alternatives' => ['A' => '(figura A)', 'B' => '(figura B)', 'C' => '(figura C)', 'D' => '(figura D)', 'E' => '(figura E)']],
        ['n' => 101, 'discipline' => 'Química', 'correct' => 'E', 'status' => 'ativa', 'content' => 'Transformações químicas e energia', 'competency' => 'CN-C7', 'skill' => 'CN-H26', 'confidence' => 'baixa', 'review' => true, 'page' => 5,
            'statement' => 'Placas solares revestidas de grafeno geram eletricidade com gotas de chuva (íons Am+ e Bn−). Ao produzir eletricidade em dias chuvosos, o grafeno [imagem oficial pendente: esquema]. (Questão interdisciplinar físico-química.)',
            'alternatives' => ['A' => 'oxida os cátions dissolvidos na água da chuva.', 'B' => 'impede a difusão da água através das placas solares.', 'C' => 'diminui a energia de ativação da reação no pseudocapacitor.', 'D' => 'forma um compósito não metálico com os íons na água da chuva.', 'E' => 'gera uma diferença de potencial pela interação dos elétrons com os cátions.']],
        ['n' => 102, 'discipline' => 'Física', 'correct' => null, 'status' => 'anulada', 'content' => 'Calor e fenômenos térmicos', 'competency' => 'CN-C6', 'skill' => 'CN-H21', 'confidence' => 'alta', 'review' => true, 'page' => 5,
            'statement' => 'Cafeteira elétrica de 700 W aquece 500 g de água de 20 °C a 100 °C em 3 minutos; calcular a eficiência energética (1 cal = 4,2 J). QUESTÃO ANULADA no gabarito oficial.',
            'alternatives' => ['A' => '100%', 'B' => '75%', 'C' => '60%', 'D' => '7,5%', 'E' => '5,1%']],
        ['n' => 103, 'discipline' => 'Física', 'correct' => 'C', 'status' => 'ativa', 'content' => 'Calor e fenômenos térmicos', 'competency' => 'CN-C6', 'skill' => 'CN-H21', 'confidence' => 'alta', 'review' => false, 'page' => 5,
            'statement' => 'No diagrama P-V do ciclo de Otto (etapas I a VI), a transformação da energia térmica em energia útil ocorre na etapa [imagem oficial pendente: diagrama P-V e quadro]',
            'alternatives' => ['A' => 'II.', 'B' => 'III.', 'C' => 'IV.', 'D' => 'V.', 'E' => 'VI.']],
        ['n' => 104, 'discipline' => 'Física', 'correct' => 'B', 'status' => 'ativa', 'content' => 'Mecânica: movimento, forças e equilíbrio', 'competency' => 'CN-C6', 'skill' => 'CN-H20', 'confidence' => 'media', 'review' => false, 'page' => 6,
            'statement' => 'Maratona aquática com corrente marinha de 30 m/min paralela à praia; nadador a 50 m/min em relação à água percorre um circuito retangular (800 m x 400 m). Em quantos minutos o nadador completará a prova? [imagem oficial pendente: diagrama do circuito]',
            'alternatives' => ['A' => '42', 'B' => '65', 'C' => '72', 'D' => '105', 'E' => '120']],
        ['n' => 105, 'discipline' => 'Biologia', 'correct' => 'B', 'status' => 'ativa', 'content' => 'Qualidade de vida das populações humanas', 'competency' => 'CN-C8', 'skill' => 'CN-H30', 'confidence' => 'alta', 'review' => false, 'page' => 6,
            'statement' => 'O HTLV-1 é um retrovírus que estimula o aumento da produção de linfócitos T (diferente do HIV, que os destrói). Uma possível consequência da infecção por HTLV-1 é o desenvolvimento de',
            'alternatives' => ['A' => 'aids.', 'B' => 'câncer.', 'C' => 'diabetes.', 'D' => 'hepatite B.', 'E' => 'hemorragia.']],
        ['n' => 106, 'discipline' => 'Física', 'correct' => 'A', 'status' => 'ativa', 'content' => 'Mecânica: movimento, forças e equilíbrio', 'competency' => 'CN-C6', 'skill' => 'CN-H20', 'confidence' => 'media', 'review' => true, 'page' => 6,
            'statement' => 'Tirinha do Calvin: ao se soltar do balanço, a gravidade modifica a direção da velocidade. Qual vetor representa a força resultante exercida pelo chão sobre Calvin no exato momento em que ele toca o chão? [imagem oficial pendente: tirinha e vetores]',
            'alternatives' => ['A' => '(vetor A)', 'B' => '(vetor B)', 'C' => '(vetor C)', 'D' => '(vetor D)', 'E' => '(vetor E)']],
        ['n' => 107, 'discipline' => 'Biologia', 'correct' => 'E', 'status' => 'ativa', 'content' => 'Ecologia e ciências ambientais', 'competency' => 'CN-C3', 'skill' => 'CN-H10', 'confidence' => 'alta', 'review' => false, 'page' => 7,
            'statement' => 'Fitorremediação: o método que retira o mercúrio de uma área contaminada, impedindo sua entrada na cadeia alimentar, é a [imagem oficial pendente: figura dos métodos]',
            'alternatives' => ['A' => 'fitoestabilização, ficando o mercúrio disponível sob a superfície das raízes das plantas.', 'B' => 'fitovolatilização, permitindo a retirada do mercúrio por plantas e a sua transferência para uma forma volátil.', 'C' => 'fitodegradação, com a degradação do mercúrio promovida por enzimas, contidas nas raízes, formando espécies menos tóxicas.', 'D' => 'fitoestimulação, com a remoção do mercúrio pela ação de microrganismos presentes nas raízes que absorvem e imobilizam o metal.', 'E' => 'fitoextração, em que as plantas que acumulam o mercúrio são cultivadas nesses locais, e a biomassa rica no metal é retirada após o crescimento.']],
        ['n' => 108, 'discipline' => 'Química', 'correct' => 'D', 'status' => 'ativa', 'content' => 'Química, tecnologias, sociedade e meio ambiente', 'competency' => 'CN-C3', 'skill' => 'CN-H8', 'confidence' => 'alta', 'review' => false, 'page' => 7,
            'statement' => 'São necessários 50 kg de bauxita para produzir 10 kg de alumínio. Em 2020 o Brasil reciclou 97,4% de um total de 4,0×10^5 t de latas de alumínio puro. Qual o valor mais próximo da massa de bauxita, em tonelada, que deixou de ser extraída?',
            'alternatives' => ['A' => '1,0 × 10^4 ton', 'B' => '3,9 × 10^5 ton', 'C' => '5,0 × 10^5 ton', 'D' => '1,9 × 10^6 ton', 'E' => '2,0 × 10^7 ton']],
        ['n' => 109, 'discipline' => 'Física', 'correct' => 'B', 'status' => 'ativa', 'content' => 'Fenômenos elétricos e magnéticos', 'competency' => 'CN-C2', 'skill' => 'CN-H5', 'confidence' => 'media', 'review' => true, 'page' => 8,
            'statement' => 'Com bateria ideal de 4,5 V, dois LEDs (3,0 V; Imáx = 1,0 mA) e dois resistores de 1,5 kΩ, qual circuito mantém ambos os LEDs acesos, cada um com Imáx? [imagem oficial pendente: circuitos]',
            'alternatives' => ['A' => '(circuito A)', 'B' => '(circuito B)', 'C' => '(circuito C)', 'D' => '(circuito D)', 'E' => '(circuito E)']],
        ['n' => 110, 'discipline' => 'Física', 'correct' => 'B', 'status' => 'ativa', 'content' => 'Fenômenos elétricos e magnéticos', 'competency' => 'CN-C2', 'skill' => 'CN-H5', 'confidence' => 'media', 'review' => true, 'page' => 8,
            'statement' => 'Lâmpadas L1 (6 V – 9 W) e L2 (12 V – 18 W) em série; fio resistivo QR de 48 cm dividido em pontos A–E; amperímetro com terminal P entre as lâmpadas e terminal S a ligar no fio. Em qual ponto o amperímetro deve ser conectado para que as lâmpadas acendam segundo as especificações? [imagem oficial pendente: circuito]',
            'alternatives' => ['A' => 'A', 'B' => 'B', 'C' => 'C', 'D' => 'D', 'E' => 'E']],
        ['n' => 111, 'discipline' => 'Química', 'correct' => 'C', 'status' => 'ativa', 'content' => 'Transformações químicas e energia', 'competency' => 'CN-C7', 'skill' => 'CN-H25', 'confidence' => 'alta', 'review' => false, 'page' => 8,
            'statement' => 'Biogás com 70% em volume de metano (massa molar 16 g/mol; volume molar 22 L/mol) substitui etanol (46 g/mol): 1 m³ de biogás substitui 0,59 L de etanol anidro (densidade 0,78 g/mL). A massa de metano necessária para substituir 10 mol de etanol é mais próxima de',
            'alternatives' => ['A' => '300 g.', 'B' => '400 g.', 'C' => '510 g.', 'D' => '590 g.', 'E' => '720 g.']],
        ['n' => 112, 'discipline' => 'Química', 'correct' => 'A', 'status' => 'ativa', 'content' => 'Compostos de carbono (química orgânica)', 'competency' => 'CN-C7', 'skill' => 'CN-H24', 'confidence' => 'alta', 'review' => false, 'page' => 9,
            'statement' => 'A nimesulida pode ser convertida em espécie carregada (mais solúvel) por tratamento com base de Brönsted-Lowry. Na estrutura, o grupamento capaz de reagir com a base de Brönsted-Lowry é o grupo [imagem oficial pendente: estrutura com grupos sulfonamida, metila, éter, fenila, nitro]',
            'alternatives' => ['A' => 'sulfonamida.', 'B' => 'metila.', 'C' => 'fenila.', 'D' => 'nitro.', 'E' => 'éter.']],
        ['n' => 113, 'discipline' => 'Biologia', 'correct' => 'A', 'status' => 'ativa', 'content' => 'Moléculas, células e tecidos', 'competency' => 'CN-C4', 'skill' => 'CN-H13', 'confidence' => 'alta', 'review' => false, 'page' => 9,
            'statement' => 'A RT-PCR usa a transcriptase reversa para sintetizar DNA complementar a partir de fitas de RNA. Nesse contexto, essa técnica é importante para detectar genes',
            'alternatives' => ['A' => 'expressos.', 'B' => 'plasmidiais.', 'C' => 'bacterianos.', 'D' => 'dominantes.', 'E' => 'autossômicos.']],
        ['n' => 114, 'discipline' => 'Física', 'correct' => 'C', 'status' => 'ativa', 'content' => 'Mecânica: movimento, forças e equilíbrio', 'competency' => 'CN-C6', 'skill' => 'CN-H20', 'confidence' => 'media', 'review' => true, 'page' => 9,
            'statement' => 'No balanceamento de roda/pneu, o centro de massa (CM) deve coincidir com o centro geométrico. Em qual ponto deve ser fixada a peça de chumbo para corrigir a posição do centro de massa? [imagem oficial pendente: roda com pontos 1–5]',
            'alternatives' => ['A' => '1', 'B' => '2', 'C' => '3', 'D' => '4', 'E' => '5']],
        ['n' => 115, 'discipline' => 'Química', 'correct' => 'D', 'status' => 'ativa', 'content' => 'Água, soluções e equilíbrio ácido-base', 'competency' => 'CN-C7', 'skill' => 'CN-H25', 'confidence' => 'alta', 'review' => false, 'page' => 9,
            'statement' => 'Soro caseiro: 2 colheres de açúcar e 2 colheres pequenas de sal em 2 L de água, concentração de íon sódio 1,4 mg/mL (NaCl = 58,5 g/mol; Na = 23 g/mol). Qual a massa, em grama, de cloreto de sódio em uma única colher pequena?',
            'alternatives' => ['A' => '0,7 g', 'B' => '1,8 g', 'C' => '2,8 g', 'D' => '3,6 g', 'E' => '7,0 g']],
        ['n' => 116, 'discipline' => 'Biologia', 'correct' => 'E', 'status' => 'ativa', 'content' => 'Origem e evolução da vida', 'competency' => 'CN-C4', 'skill' => 'CN-H16', 'confidence' => 'alta', 'review' => false, 'page' => 10,
            'statement' => 'No cladograma de mamíferos (Monotremata, Marsupialia, Placentalia), percebem-se perdas e ganhos nos padrões de reprodução/nutrição dos embriões que envolvem o(a) [imagem oficial pendente: cladograma]',
            'alternatives' => ['A' => 'aumento no número de descendentes por ninhada.', 'B' => 'mudança no tipo de fecundação de externa para interna.', 'C' => 'redução da versatilidade de reprodução, que se torna unicamente sexuada.', 'D' => 'desenvolvimento embrionário, que passa do meio aquático para o terrestre.', 'E' => 'diminuição da vesícula vitelínica, associada ao desenvolvimento da lactação.']],
        ['n' => 117, 'discipline' => 'Física', 'correct' => 'D', 'status' => 'ativa', 'content' => 'Oscilações, ondas, óptica e radiação', 'competency' => 'CN-C1', 'skill' => 'CN-H1', 'confidence' => 'alta', 'review' => false, 'page' => 10,
            'statement' => 'Um radar emite ondas de rádio (frequência f0) refletidas pela ambulância que se aproxima, retornando com frequência fr. Durante a aproximação, como o operador percebe o som da sirene e qual é a relação entre fr e f0 medidas pelo radar?',
            'alternatives' => ['A' => 'Mais grave do que o som emitido e fr < f0.', 'B' => 'Mais agudo do que o som emitido e fr < f0.', 'C' => 'Mais agudo do que o som emitido e fr = f0.', 'D' => 'Mais agudo do que o som emitido e fr > f0.', 'E' => 'Mais grave do que o som emitido e fr > f0.']],
        ['n' => 118, 'discipline' => 'Física', 'correct' => 'C', 'status' => 'ativa', 'content' => 'Oscilações, ondas, óptica e radiação', 'competency' => 'CN-C6', 'skill' => 'CN-H20', 'confidence' => 'media', 'review' => true, 'page' => 10,
            'statement' => 'Mirascópio 3D: dois espelhos côncavos E1 e E2 (vértice de um coincide com o foco do outro) formam uma imagem tridimensional. A natureza da imagem formada e a distância vertical entre cada ponto objeto e seu correspondente ponto imagem são [imagem oficial pendente: esquema com 5 cm e 3,8 cm]',
            'alternatives' => ['A' => 'real e 5 cm.', 'B' => 'real e 3,8 cm.', 'C' => 'real e 7,6 cm.', 'D' => 'virtual e 7,6 cm.', 'E' => 'virtual e 3,8 cm.']],
        ['n' => 119, 'discipline' => 'Física', 'correct' => 'B', 'status' => 'ativa', 'content' => 'Energia, trabalho e potência', 'competency' => 'CN-C6', 'skill' => 'CN-H20', 'confidence' => 'alta', 'review' => false, 'page' => 11,
            'statement' => 'Carros modernos têm crumple zone (região deformável). Considerando carro, ocupantes e muro como sistema isolado, o crumple zone aumenta a segurança porque, durante uma colisão, a deformação da estrutura do carro [imagem oficial pendente: figura]',
            'alternatives' => ['A' => 'aciona os airbags do veículo.', 'B' => 'absorve a energia cinética do sistema.', 'C' => 'consome a quantidade de movimento do sistema.', 'D' => 'cria uma barreira de proteção para seus ocupantes.', 'E' => 'diminui a velocidade do centro de massa do sistema.']],
        ['n' => 120, 'discipline' => 'Química', 'correct' => 'C', 'status' => 'ativa', 'content' => 'Transformações químicas e energia', 'competency' => 'CN-C7', 'skill' => 'CN-H24', 'confidence' => 'alta', 'review' => false, 'page' => 11,
            'statement' => 'Célula a combustível microbiana (CCM): ânodo CH3COO− + 2 H2O → 2 CO2 + 7 H+ + 8 e−; cátodo 4 H+ + O2 + 4 e− → 2 H2O. Qual equação representa a reação global da CCM?',
            'alternatives' => ['A' => 'CH3COO− (aq) + O2 (g) → 2 CO2 (g) + 3 H+ (aq)', 'B' => 'CO2 (g) + O2 (g) + H+ (aq) → H2O (l) + CH3COO− (aq)', 'C' => 'CH3COO− (aq) + H+ (aq) + 2 O2 (g) → 2 CO2 (g) + 2 H2O (l)', 'D' => 'CH3COO− (aq) + 6 H2O (l) → 2 CO2 (g) + 2 O2 (g) + 15 H+ (aq)', 'E' => '2 CO2 (g) + 11 H+ (aq) + O2 (g) → CH3COO− (aq) + 4 H2O (l)']],
        ['n' => 121, 'discipline' => 'Química', 'correct' => 'E', 'status' => 'ativa', 'content' => 'Compostos de carbono (química orgânica)', 'competency' => 'CN-C7', 'skill' => 'CN-H24', 'confidence' => 'alta', 'review' => false, 'page' => 11,
            'statement' => 'A concepção científica atual define os compostos orgânicos como substâncias',
            'alternatives' => ['A' => 'benéficas à saúde humana.', 'B' => 'capazes de serem biodegradadas.', 'C' => 'formadas a partir de gás carbônico.', 'D' => 'produzidas sem o uso de agrotóxicos.', 'E' => 'contendo carbono como elemento principal.']],
        ['n' => 122, 'discipline' => 'Biologia', 'correct' => 'E', 'status' => 'ativa', 'content' => 'Ecologia e ciências ambientais', 'competency' => 'CN-C3', 'skill' => 'CN-H9', 'confidence' => 'media', 'review' => true, 'page' => 12,
            'statement' => 'Esquema da ação de procariontes no ciclo do nitrogênio e do carbono (etapas numeradas 1–5). Em qual etapa numerada ocorre uma transformação redox como a que ocorre nos procariontes nitrificantes? [imagem oficial pendente: esquema dos ciclos]',
            'alternatives' => ['A' => '1', 'B' => '2', 'C' => '3', 'D' => '4', 'E' => '5']],
        ['n' => 123, 'discipline' => 'Química', 'correct' => 'C', 'status' => 'ativa', 'content' => 'Química, tecnologias, sociedade e meio ambiente', 'competency' => 'CN-C5', 'skill' => 'CN-H17', 'confidence' => 'media', 'review' => true, 'page' => 12,
            'statement' => 'Gráfico das emissões (CO2, HC, CO, NO, O2) de um motor a gasolina em diferentes razões ar/combustível. Na condição de razão ar/combustível igual a 18, haverá uma emissão [imagem oficial pendente: gráfico]',
            'alternatives' => ['A' => 'baixa de O2 e alta de NO.', 'B' => 'baixa de NO e alta de HC.', 'C' => 'baixa de CO e alta de CO2.', 'D' => 'baixa de HC e alta de CO.', 'E' => 'baixa de CO2 e alta de HC.']],
        ['n' => 124, 'discipline' => 'Física', 'correct' => 'A', 'status' => 'ativa', 'content' => 'Oscilações, ondas, óptica e radiação', 'competency' => 'CN-C1', 'skill' => 'CN-H1', 'confidence' => 'media', 'review' => true, 'page' => 13,
            'statement' => 'Acústica de sala de aula: a 1 m o nível sonoro da fala é 60 dB e diminui com a distância; ruído de fundo até 45 dB; para ser compreendida a fala deve estar 5 dB acima do ruído. A maior distância que um estudante pode estar do professor para ainda compreender é mais próxima de [imagem oficial pendente: infográfico]',
            'alternatives' => ['A' => '3,0 m.', 'B' => '4,5 m.', 'C' => '6,5 m.', 'D' => '8,0 m.', 'E' => '9,5 m.']],
        ['n' => 125, 'discipline' => 'Biologia', 'correct' => 'A', 'status' => 'ativa', 'content' => 'Moléculas, células e tecidos', 'competency' => 'CN-C8', 'skill' => 'CN-H29', 'confidence' => 'alta', 'review' => false, 'page' => 13,
            'statement' => 'Imergir espigas de milho em água fervente e depois gelada preserva o sabor adocicado (parte da glicose não vira amido). Utilizando esse procedimento, o sabor foi conservado porque houve',
            'alternatives' => ['A' => 'desnaturação enzimática pela alta temperatura.', 'B' => 'conversão de nutrientes pela redução de temperatura.', 'C' => 'degradação das reservas nutritivas pelo choque térmico.', 'D' => 'impedimento da entrada de oxigênio pela fervura da água.', 'E' => 'desidratação dos grãos por causa da alteração da temperatura.']],
        ['n' => 126, 'discipline' => 'Física', 'correct' => 'E', 'status' => 'ativa', 'content' => 'Calor e fenômenos térmicos', 'competency' => 'CN-C6', 'skill' => 'CN-H21', 'confidence' => 'alta', 'review' => false, 'page' => 13,
            'statement' => 'Aquecedor solar com coletores e reservatório térmico. O processo pelo qual ocorre transferência de calor dos coletores solares para o reservatório térmico é a [imagem oficial pendente: esquema]',
            'alternatives' => ['A' => 'difusão.', 'B' => 'absorção.', 'C' => 'condução.', 'D' => 'irradiação.', 'E' => 'convecção.']],
        ['n' => 127, 'discipline' => 'Biologia', 'correct' => 'D', 'status' => 'ativa', 'content' => 'Ecologia e ciências ambientais', 'competency' => 'CN-C4', 'skill' => 'CN-H14', 'confidence' => 'media', 'review' => true, 'page' => 13,
            'statement' => 'Fluxograma: urbanização → ausência de saneamento básico → contaminação da água → redução da biodiversidade aquática → riscos à saúde humana (arboviroses). Nesse contexto, como a urbanização está causando riscos à saúde humana? [imagem oficial pendente: fluxograma]',
            'alternatives' => ['A' => 'Disseminando verminoses.', 'B' => 'Causando a eutrofização de lagoas.', 'C' => 'Aumentando a chance de contato com coliformes.', 'D' => 'Diminuindo a população de predadores aquáticos.', 'E' => 'Aproximando as pessoas das áreas de ocorrência de mosquitos.']],
        ['n' => 128, 'discipline' => 'Biologia', 'correct' => 'D', 'status' => 'ativa', 'content' => 'Qualidade de vida das populações humanas', 'competency' => 'CN-C4', 'skill' => 'CN-H14', 'confidence' => 'alta', 'review' => false, 'page' => 14,
            'statement' => 'Microplásticos aderem a poluentes apolares persistentes (derivados de pesticidas lipossolúveis), com proporcionalidade entre solubilidade e concentração nos tecidos. Em animais vertebrados, essa associação de poluentes será preferencialmente acumulada no tecido',
            'alternatives' => ['A' => 'ósseo.', 'B' => 'nervoso.', 'C' => 'epitelial.', 'D' => 'adiposo.', 'E' => 'sanguíneo.']],
        ['n' => 129, 'discipline' => 'Física', 'correct' => 'D', 'status' => 'ativa', 'content' => 'Oscilações, ondas, óptica e radiação', 'competency' => 'CN-C1', 'skill' => 'CN-H2', 'confidence' => 'alta', 'review' => false, 'page' => 14,
            'statement' => 'Em aeroportos, pede-se retirar computadores das malas para inspeção isolada por raios X. Que explicação física justifica esse procedimento?',
            'alternatives' => ['A' => 'Os raios X não interagem com os componentes metálicos do computador, o que impede a formação de imagens.', 'B' => 'Os raios X desmagnetizam o disco rígido do computador, quando refratados pelos componentes metálicos das bagagens de mão.', 'C' => 'Os raios X aquecem os materiais metálicos encontrados em bagagens de mão, quando refletidos pelos componentes do computador.', 'D' => 'Os raios X não atravessam os componentes densos do computador, o que impede a visualização de objetos que estão à frente ou atrás deles.', 'E' => 'Os raios X ionizam os materiais metálicos normalmente encontrados em bagagens de mão, quando difratados pelos componentes do computador.']],
        ['n' => 130, 'discipline' => 'Biologia', 'correct' => 'E', 'status' => 'ativa', 'content' => 'Qualidade de vida das populações humanas', 'competency' => 'CN-C4', 'skill' => 'CN-H14', 'confidence' => 'media', 'review' => true, 'page' => 14,
            'statement' => 'Compostos nitrosos (mutagênicos) podem ser obtidos pela reação entre o nitrito de sódio (conservante de carnes) e o ácido clorídrico; o ácido nitroso reage com aminas formando compostos nitrosos. Em qual órgão esse processo será iniciado?',
            'alternatives' => ['A' => 'Rim.', 'B' => 'Fígado.', 'C' => 'Intestino.', 'D' => 'Pâncreas.', 'E' => 'Estômago.']],
        ['n' => 131, 'discipline' => 'Biologia', 'correct' => 'B', 'status' => 'ativa', 'content' => 'Ecologia e ciências ambientais', 'competency' => 'CN-C4', 'skill' => 'CN-H16', 'confidence' => 'alta', 'review' => false, 'page' => 14,
            'statement' => 'Em sistemas agroflorestais (SAFs), ocorrem mudanças graduais na estrutura e composição das comunidades vegetais ao longo do tempo, aumentando a diversidade. O conjunto dessas mudanças graduais é análogo ao processo natural denominado',
            'alternatives' => ['A' => 'rotação de culturas.', 'B' => 'sucessão ecológica.', 'C' => 'coevolução específica.', 'D' => 'adaptação por seleção.', 'E' => 'convergência adaptativa.']],
        ['n' => 132, 'discipline' => 'Biologia', 'correct' => 'B', 'status' => 'ativa', 'content' => 'Qualidade de vida das populações humanas', 'competency' => 'CN-C4', 'skill' => 'CN-H14', 'confidence' => 'alta', 'review' => false, 'page' => 14,
            'statement' => 'Fibras musculares lentas (vermelhas; muitas mitocôndrias, bem vascularizadas) e rápidas (brancas; poucas mitocôndrias). Um atleta com maior proporção de fibras brancas teria mais vantagens na prova de',
            'alternatives' => ['A' => 'Triatlo.', 'B' => 'Salto em altura.', 'C' => 'Marcha atlética.', 'D' => 'Maratona aquática.', 'E' => 'Ciclismo em estrada.']],
        ['n' => 133, 'discipline' => 'Biologia', 'correct' => 'D', 'status' => 'ativa', 'content' => 'Origem e evolução da vida', 'competency' => 'CN-C4', 'skill' => 'CN-H16', 'confidence' => 'alta', 'review' => false, 'page' => 15,
            'statement' => 'Corais-verdadeiras (peçonhentas) e falsas-corais (sem peçonha) têm coloração semelhante. Qual é a vantagem dessa similaridade para as falsas-corais? [imagem oficial pendente: fotografias]',
            'alternatives' => ['A' => 'Facilita a captura de presas.', 'B' => 'Diminui a competição por recursos.', 'C' => 'Possibilita a geração de indivíduos híbridos.', 'D' => 'Reduz a possibilidade de sofrerem predação.', 'E' => 'Otimiza o encontro de parceiros reprodutivos.']],
        ['n' => 134, 'discipline' => 'Biologia', 'correct' => 'D', 'status' => 'ativa', 'content' => 'Identidade dos seres vivos', 'competency' => 'CN-C4', 'skill' => 'CN-H14', 'confidence' => 'alta', 'review' => false, 'page' => 15,
            'statement' => 'O exoesqueleto dos crustáceos (quitina + sais calcários) é duro e limita o crescimento. Para superar essa limitação, o exoesqueleto deve ser',
            'alternatives' => ['A' => 'formado somente na fase adulta do animal.', 'B' => 'fragmentado para expansão nas áreas de articulação.', 'C' => 'modelado continuamente para ajuste ao tamanho do corpo.', 'D' => 'substituído por meio de mudas que ocorrem periodicamente.', 'E' => 'impregnado por pequena quantidade de sais para sua distensão.']],
        ['n' => 135, 'discipline' => 'Biologia', 'correct' => 'B', 'status' => 'ativa', 'content' => 'Hereditariedade e diversidade da vida', 'competency' => 'CN-C4', 'skill' => 'CN-H13', 'confidence' => 'media', 'review' => true, 'page' => 15,
            'statement' => 'Daltonismo: herança recessiva ligada ao X. Casal de homem não daltônico e mulher não daltônica portadora; qual heredograma contém todas as possibilidades de genótipo para o bebê? [imagem oficial pendente: heredogramas A–E]',
            'alternatives' => ['A' => '(heredograma A)', 'B' => '(heredograma B)', 'C' => '(heredograma C)', 'D' => '(heredograma D)', 'E' => '(heredograma E)']],

        // ===================== Matemática (136–180) =====================
        ['n' => 136, 'discipline' => 'Matemática', 'correct' => 'C', 'status' => 'ativa', 'content' => 'Conhecimentos algébricos', 'competency' => 'MT-C5', 'skill' => 'MT-H21', 'confidence' => 'alta', 'review' => false, 'page' => 16,
            'statement' => 'Custo total de produção de mochilas cresce de forma linear: 30→R$1.050,00; 50→R$1.650,00; 100→R$3.150,00. O custo total, em real, para a produção de 80 mochilas será',
            'alternatives' => ['A' => '2400,00.', 'B' => '2520,00.', 'C' => '2550,00.', 'D' => '2700,00.', 'E' => '2800,00.']],
        ['n' => 137, 'discipline' => 'Matemática', 'correct' => 'E', 'status' => 'ativa', 'content' => 'Conhecimentos de estatística e probabilidade', 'competency' => 'MT-C7', 'skill' => 'MT-H27', 'confidence' => 'alta', 'review' => false, 'page' => 16,
            'statement' => 'Umidade relativa do ar (%) em seis meses: Maio 66, Jun 64, Jul 54, Ago 46, Set 60, Out 64. A mediana desses dados, em porcentagem, foi',
            'alternatives' => ['A' => '56.', 'B' => '58.', 'C' => '59.', 'D' => '60.', 'E' => '62.']],
        ['n' => 138, 'discipline' => 'Matemática', 'correct' => 'C', 'status' => 'ativa', 'content' => 'Variação de grandezas e proporcionalidade', 'competency' => 'MT-C4', 'skill' => 'MT-H16', 'confidence' => 'alta', 'review' => false, 'page' => 16,
            'statement' => 'Serviço de R$71.250,00; 40% para três engenheiros, proporcional às horas: I 4 dias × 5,5 h; II 5 dias × 4 h; III 6 dias × 2,5 h. Qual a maior diferença, em real, entre os valores recebidos por dois desses engenheiros?',
            'alternatives' => ['A' => '1000', 'B' => '1500', 'C' => '3500', 'D' => '3800', 'E' => '5250']],
        ['n' => 139, 'discipline' => 'Matemática', 'correct' => 'E', 'status' => 'ativa', 'content' => 'Conhecimentos numéricos', 'competency' => 'MT-C1', 'skill' => 'MT-H2', 'confidence' => 'media', 'review' => true, 'page' => 16,
            'statement' => 'Hospital com 7 cardiologistas e 6 neurologistas; equipe de 5 médicos com pelo menos 3 cardiologistas. Qual expressão representa o número máximo de maneiras de formar a equipe? [imagem oficial pendente: expressões com combinações]',
            'alternatives' => ['A' => '(expressão A)', 'B' => '(expressão B)', 'C' => '(expressão C)', 'D' => '(expressão D)', 'E' => '(expressão E)']],
        ['n' => 140, 'discipline' => 'Matemática', 'correct' => 'B', 'status' => 'ativa', 'content' => 'Conhecimentos de estatística e probabilidade', 'competency' => 'MT-C7', 'skill' => 'MT-H28', 'confidence' => 'alta', 'review' => false, 'page' => 17,
            'statement' => 'Dois semáforos ficam 15 s vermelhos a cada 60 s (probabilidade 15/60 cada). Após uma redução igual no tempo de vermelho, a probabilidade de encontrar ambos vermelhos (eventos independentes) passa a ser 4/100. A redução do tempo de vermelho, em segundo, foi de',
            'alternatives' => ['A' => '1,35.', 'B' => '3,00.', 'C' => '9,00.', 'D' => '12,60.', 'E' => '13,80.']],
        ['n' => 141, 'discipline' => 'Matemática', 'correct' => 'E', 'status' => 'ativa', 'content' => 'Variação de grandezas e proporcionalidade', 'competency' => 'MT-C4', 'skill' => 'MT-H15', 'confidence' => 'alta', 'review' => false, 'page' => 17,
            'statement' => 'Densidade demográfica = habitantes/área. Região Q tem área igual a 3/4 da de R e número de habitantes igual à metade do de R. A expressão que relaciona d(Q) e d(R) é',
            'alternatives' => ['A' => 'd(Q) = (1/4) d(R)', 'B' => 'd(Q) = (1/2) d(R)', 'C' => 'd(Q) = (3/4) d(R)', 'D' => 'd(Q) = (3/2) d(R)', 'E' => 'd(Q) = (2/3) d(R)']],
        ['n' => 142, 'discipline' => 'Matemática', 'correct' => 'D', 'status' => 'ativa', 'content' => 'Conhecimentos numéricos', 'competency' => 'MT-C1', 'skill' => 'MT-H3', 'confidence' => 'alta', 'review' => false, 'page' => 17,
            'statement' => 'Telas de celular: celular 1 mede 3 1/2 polegadas e celular 2 mede 4 5/6 polegadas. A diferença de tamanho, em valor absoluto, entre as telas do celular 2 e do celular 1, com uma casa decimal, é',
            'alternatives' => ['A' => '0,1.', 'B' => '0,5.', 'C' => '1,0.', 'D' => '1,3.', 'E' => '1,8.']],
        ['n' => 143, 'discipline' => 'Matemática', 'correct' => 'A', 'status' => 'ativa', 'content' => 'Conhecimentos numéricos', 'competency' => 'MT-C1', 'skill' => 'MT-H2', 'confidence' => 'media', 'review' => true, 'page' => 18,
            'statement' => 'Apartamento em 100 parcelas mensais com acréscimo percentual fixo a partir da 2ª; a imobiliária paga as parcelas do mês de aniversário do comprador (maio). Para minimizar o total pago, qual mês o cliente deverá escolher para realizar a compra?',
            'alternatives' => ['A' => 'Fevereiro.', 'B' => 'Abril.', 'C' => 'Maio.', 'D' => 'Junho.', 'E' => 'Agosto.']],
        ['n' => 144, 'discipline' => 'Matemática', 'correct' => 'D', 'status' => 'ativa', 'content' => 'Conhecimentos geométricos', 'competency' => 'MT-C2', 'skill' => 'MT-H8', 'confidence' => 'media', 'review' => true, 'page' => 18,
            'statement' => 'Sistema de polias (r = 4 cm, R = 8 cm; arco de 150°; segmentos retos de 15 cm) com correia ajustada. Considere π ≈ 3. A medida do comprimento da correia, em centímetro, é [imagem oficial pendente: figura das polias]',
            'alternatives' => ['A' => '54.', 'B' => '60.', 'C' => '66.', 'D' => '68.', 'E' => '72.']],
        ['n' => 145, 'discipline' => 'Matemática', 'correct' => 'C', 'status' => 'ativa', 'content' => 'Conhecimentos geométricos', 'competency' => 'MT-C2', 'skill' => 'MT-H8', 'confidence' => 'media', 'review' => true, 'page' => 18,
            'statement' => 'Três postos de saúde equidistantes entre si (10 km) e equidistantes do hospital H, todos no mesmo plano. A distância, em quilômetro, entre o hospital e cada posto está entre [imagem oficial pendente: esquema]',
            'alternatives' => ['A' => '2 e 3.', 'B' => '4 e 5.', 'C' => '5 e 6.', 'D' => '7 e 8.', 'E' => '8 e 9.']],
        ['n' => 146, 'discipline' => 'Matemática', 'correct' => 'A', 'status' => 'ativa', 'content' => 'Conhecimentos algébricos', 'competency' => 'MT-C5', 'skill' => 'MT-H20', 'confidence' => 'media', 'review' => true, 'page' => 19,
            'statement' => 'Amortecedores: oscilações senoidais por 20 min (9 min em asfalto, 11 min em estrada de chão); amplitudes constantes em cada superfície e amplitude no asfalto menor que na estrada de chão. Qual gráfico descreve um amortecedor aprovado? [imagem oficial pendente: gráficos A–E]',
            'alternatives' => ['A' => '(gráfico A)', 'B' => '(gráfico B)', 'C' => '(gráfico C)', 'D' => '(gráfico D)', 'E' => '(gráfico E)']],
        ['n' => 147, 'discipline' => 'Matemática', 'correct' => 'A', 'status' => 'ativa', 'content' => 'Conhecimentos geométricos', 'competency' => 'MT-C2', 'skill' => 'MT-H8', 'confidence' => 'alta', 'review' => false, 'page' => 20,
            'statement' => 'Com k metros de cerca, o jardim (triângulo equilátero, quadrado ou hexágono regular) de maior área. O jardineiro escolherá a forma de',
            'alternatives' => ['A' => 'hexágono regular, pois a área será k²√3/24.', 'B' => 'hexágono regular, pois a área será 3√3 k²/2.', 'C' => 'quadrado, pois a área será k²/16.', 'D' => 'triângulo equilátero, pois a área será k²√3/36.', 'E' => 'triângulo equilátero, pois a área será k²√3/4.']],
        ['n' => 148, 'discipline' => 'Matemática', 'correct' => 'D', 'status' => 'ativa', 'content' => 'Grandezas e medidas', 'competency' => 'MT-C3', 'skill' => 'MT-H12', 'confidence' => 'media', 'review' => true, 'page' => 20,
            'statement' => 'Ônibus A (250 m/min, do terminal 1) e B (150 m/min, do terminal 2) percorrem 9000 m monitorados por 5 câmeras (alcances I 1/5, II 3/10, III 1/10, IV 1/10, V 3/10). Qual câmera registra o encontro de A e B? [imagem oficial pendente: esquema das câmeras]',
            'alternatives' => ['A' => 'I', 'B' => 'II', 'C' => 'III', 'D' => 'IV', 'E' => 'V']],
        ['n' => 149, 'discipline' => 'Matemática', 'correct' => 'E', 'status' => 'ativa', 'content' => 'Conhecimentos de estatística e probabilidade', 'competency' => 'MT-C7', 'skill' => 'MT-H28', 'confidence' => 'alta', 'review' => false, 'page' => 21,
            'statement' => 'Cifra de César (alfabeto de 26 letras); cada tentativa frustrada é eliminada nas seguintes. A probabilidade de descobrir o padrão apenas na terceira tentativa é dada por',
            'alternatives' => ['A' => '1/25 + 1/25 + 1/25', 'B' => '24/25 + 23/24 + 1/23', 'C' => '(1/25) × (1/24) × (1/23)', 'D' => '(24/25) × (23/25) × (1/25)', 'E' => '(24/25) × (23/24) × (1/23)']],
        ['n' => 150, 'discipline' => 'Matemática', 'correct' => 'C', 'status' => 'ativa', 'content' => 'Conhecimentos algébricos', 'competency' => 'MT-C5', 'skill' => 'MT-H21', 'confidence' => 'alta', 'review' => false, 'page' => 21,
            'statement' => 'Terremotos na escala Richter: M2 − M1 = (2/3) log(E2/E1). Com M1 = 6,9 e energia liberada igual a um décimo da do segundo terremoto, o valor aproximado de M2 (uma casa decimal) é',
            'alternatives' => ['A' => '5,4.', 'B' => '6,2.', 'C' => '7,6.', 'D' => '8,2.', 'E' => '8,4.']],
        ['n' => 151, 'discipline' => 'Matemática', 'correct' => 'D', 'status' => 'ativa', 'content' => 'Conhecimentos geométricos', 'competency' => 'MT-C2', 'skill' => 'MT-H8', 'confidence' => 'alta', 'review' => false, 'page' => 22,
            'statement' => 'Folha 10 cm × 20 cm forma a superfície lateral de um cilindro (com fundo e tampa). Entre as duas embalagens possíveis, a de maior capacidade tem volume, em centímetro cúbico, igual a',
            'alternatives' => ['A' => '4000 π', 'B' => '2000 π', 'C' => '4000/π', 'D' => '1000/π', 'E' => '500/π']],
        ['n' => 152, 'discipline' => 'Matemática', 'correct' => 'B', 'status' => 'ativa', 'content' => 'Conhecimentos de estatística e probabilidade', 'competency' => 'MT-C6', 'skill' => 'MT-H24', 'confidence' => 'media', 'review' => true, 'page' => 22,
            'statement' => 'Receitas anuais (2014–2021, em milhão de reais) com reta de tendência. A estimativa da receita, em milhão de reais, para 2026, obtida a partir da reta, é [imagem oficial pendente: gráfico de dispersão e reta]',
            'alternatives' => ['A' => '7.', 'B' => '8.', 'C' => '9.', 'D' => '10.', 'E' => '11.']],
        ['n' => 153, 'discipline' => 'Matemática', 'correct' => 'B', 'status' => 'ativa', 'content' => 'Conhecimentos algébricos', 'competency' => 'MT-C6', 'skill' => 'MT-H20', 'confidence' => 'media', 'review' => true, 'page' => 23,
            'statement' => 'Tanque (paralelepípedo) com dois anteparos (alturas H/2 e H/4) dividindo a base em três retângulos congruentes; enchimento a vazão constante em 12 h. Qual gráfico descreve a maior altura de coluna de água ao longo do enchimento? [imagem oficial pendente: gráficos A–E]',
            'alternatives' => ['A' => '(gráfico A)', 'B' => '(gráfico B)', 'C' => '(gráfico C)', 'D' => '(gráfico D)', 'E' => '(gráfico E)']],
        ['n' => 154, 'discipline' => 'Matemática', 'correct' => 'C', 'status' => 'ativa', 'content' => 'Conhecimentos de estatística e probabilidade', 'competency' => 'MT-C7', 'skill' => 'MT-H27', 'confidence' => 'alta', 'review' => false, 'page' => 24,
            'statement' => 'Tempo de leitura de contratos (min): A 36, B 17, C 27, D 13, E 13, F 13. O tempo médio, em minuto, com uma casa decimal, é aproximadamente',
            'alternatives' => ['A' => '13,0.', 'B' => '15,0.', 'C' => '19,8.', 'D' => '20,0.', 'E' => '23,3.']],
        ['n' => 155, 'discipline' => 'Matemática', 'correct' => 'E', 'status' => 'ativa', 'content' => 'Conhecimentos geométricos', 'competency' => 'MT-C2', 'skill' => 'MT-H8', 'confidence' => 'alta', 'review' => false, 'page' => 24,
            'statement' => 'Sensor cobre um setor circular (ângulo α, raio R). Tipos: I 15°/20 m; II 30°/22 m; III 40°/12 m; IV 60°/16 m; V 90°/10 m. Cobrir no mínimo 70 m² com o menor preço (π ≈ 3). O proprietário deverá adquirir o sensor do tipo',
            'alternatives' => ['A' => 'I.', 'B' => 'II.', 'C' => 'III.', 'D' => 'IV.', 'E' => 'V.']],
        ['n' => 156, 'discipline' => 'Matemática', 'correct' => 'B', 'status' => 'ativa', 'content' => 'Conhecimentos algébricos', 'competency' => 'MT-C5', 'skill' => 'MT-H19', 'confidence' => 'alta', 'review' => false, 'page' => 24,
            'statement' => 'App de transporte: R$2,00 de valor fixo + R$0,26 por minuto (T) + R$1,40 por km (D). A expressão que fornece o valor V a ser pago é',
            'alternatives' => ['A' => '2,00F + 0,26T + 1,40D', 'B' => '2,00 + 0,26T + 1,40D', 'C' => '2,00 + 0,26T + D', 'D' => '0,26T + 1,40D', 'E' => 'F + T + D']],
        ['n' => 157, 'discipline' => 'Matemática', 'correct' => 'D', 'status' => 'ativa', 'content' => 'Grandezas e medidas', 'competency' => 'MT-C3', 'skill' => 'MT-H12', 'confidence' => 'alta', 'review' => false, 'page' => 25,
            'statement' => 'Piscina de 2.500.000 L com vazão de 6.000 L/min. Segunda piscina de 2.750.000 L deve encher em tempo 20% maior. A vazão do sistema da segunda piscina, em litro por minuto, é',
            'alternatives' => ['A' => '8250.', 'B' => '7920.', 'C' => '6545.', 'D' => '5500.', 'E' => '5280.']],
        ['n' => 158, 'discipline' => 'Matemática', 'correct' => 'C', 'status' => 'ativa', 'content' => 'Grandezas e medidas', 'competency' => 'MT-C3', 'skill' => 'MT-H10', 'confidence' => 'alta', 'review' => false, 'page' => 25,
            'statement' => 'Fluxo φ é diretamente proporcional à vazão (mL/s) e inversamente proporcional à área da membrana (cm²). A unidade de medida adequada para descrever o fluxo φ é',
            'alternatives' => ['A' => 'mL·s·cm²', 'B' => '(mL/s)·cm²', 'C' => 'mL/(cm²·s)', 'D' => '(cm²·s)/mL', 'E' => 'cm²/(mL·s)']],
        ['n' => 159, 'discipline' => 'Matemática', 'correct' => 'C', 'status' => 'ativa', 'content' => 'Conhecimentos numéricos', 'competency' => 'MT-C1', 'skill' => 'MT-H3', 'confidence' => 'media', 'review' => true, 'page' => 25,
            'statement' => 'Promoção: comprando ao menos 35 L do Tipo A ganha a máscara. Defensivo A R$4,20/L (rende 0,5 ha/L); B R$3,00/L (rende 0,4 ha/L); máscara R$12,50. Aplicar em 20 ha levando uma máscara. O valor mínimo, em real, a ser gasto é [imagem oficial pendente: cartaz da promoção]',
            'alternatives' => ['A' => '147,00.', 'B' => '150,00.', 'C' => '162,50.', 'D' => '165,75.', 'E' => '168,00.']],
        ['n' => 160, 'discipline' => 'Matemática', 'correct' => 'C', 'status' => 'ativa', 'content' => 'Conhecimentos algébricos', 'competency' => 'MT-C5', 'skill' => 'MT-H21', 'confidence' => 'alta', 'review' => false, 'page' => 25,
            'statement' => 'Doceira: taxa de entrega R$10,00 e porção R$25,00. Nova taxa R$15,00, mantendo o total de 5 porções igual. A partir da próxima semana, o novo valor cobrado por porção será',
            'alternatives' => ['A' => '12,50', 'B' => '20,00', 'C' => '24,00', 'D' => '30,00', 'E' => '37,50']],
        ['n' => 161, 'discipline' => 'Matemática', 'correct' => 'A', 'status' => 'ativa', 'content' => 'Conhecimentos de estatística e probabilidade', 'competency' => 'MT-C7', 'skill' => 'MT-H29', 'confidence' => 'media', 'review' => true, 'page' => 26,
            'statement' => 'Empresa com 400 funcionários em três setores; gráfico por setor e faixa etária. A maior probabilidade é que o funcionário sorteado esteja na faixa etária [imagem oficial pendente: gráfico de barras empilhadas]',
            'alternatives' => ['A' => 'entre 25 e 45 anos, pois é a faixa etária com maior quantidade de funcionários.', 'B' => 'entre 25 e 45 anos, pois é a única faixa etária cujas porcentagens são maiores do que as porcentagens mínimas de cada setor.', 'C' => 'até 25 anos, pois é a única faixa etária cujos percentuais associados aos setores aumentam com o aumento da quantidade de funcionários por setor.', 'D' => 'até 25 anos, pois é a faixa etária que apresenta maior quantidade de funcionários no setor de produção, que é o setor que emprega metade dos funcionários dessa empresa.', 'E' => 'a partir de 45 anos, pois a soma das porcentagens associadas a essa faixa etária é 110%.']],
        ['n' => 162, 'discipline' => 'Matemática', 'correct' => 'C', 'status' => 'ativa', 'content' => 'Conhecimentos geométricos', 'competency' => 'MT-C2', 'skill' => 'MT-H6', 'confidence' => 'media', 'review' => true, 'page' => 26,
            'statement' => 'Jogo: trajetória ABCDEF em planos ortogonais ao plano da base que contém F. A projeção ortogonal, sobre o plano da base, da trajetória ABCDEF é [imagem oficial pendente: figura 3D e projeções A–E]',
            'alternatives' => ['A' => '(projeção A)', 'B' => '(projeção B)', 'C' => '(projeção C)', 'D' => '(projeção D)', 'E' => '(projeção E)']],
        ['n' => 163, 'discipline' => 'Matemática', 'correct' => 'A', 'status' => 'ativa', 'content' => 'Conhecimentos numéricos', 'competency' => 'MT-C1', 'skill' => 'MT-H3', 'confidence' => 'alta', 'review' => false, 'page' => 27,
            'statement' => 'Visão humana enxerga até 100 micrômetros (1 µm = 10⁻³ mm); hemácias medem 0,007 mm. Ocular amplia 10×; objetivas I 2×, II 10×, III 15×, IV 1,1×, V 1,4×. A lente objetiva de menor ampliação que permita, com a ocular, visualizar hemácias é a',
            'alternatives' => ['A' => 'I.', 'B' => 'II.', 'C' => 'III.', 'D' => 'IV.', 'E' => 'V.']],
        ['n' => 164, 'discipline' => 'Matemática', 'correct' => 'B', 'status' => 'ativa', 'content' => 'Conhecimentos de estatística e probabilidade', 'competency' => 'MT-C7', 'skill' => 'MT-H27', 'confidence' => 'alta', 'review' => false, 'page' => 27,
            'statement' => 'Ao calcular a média de 4 provas, um estudante dividiu por 5 (em vez de 4) e obteve média 1 unidade menor do que a correta. O valor correto da média das notas é',
            'alternatives' => ['A' => '4.', 'B' => '5.', 'C' => '6.', 'D' => '19.', 'E' => '21.']],
        ['n' => 165, 'discipline' => 'Matemática', 'correct' => 'B', 'status' => 'ativa', 'content' => 'Conhecimentos numéricos', 'competency' => 'MT-C1', 'skill' => 'MT-H2', 'confidence' => 'media', 'review' => true, 'page' => 27,
            'statement' => 'Teclado alfanumérico; senha de 5 caracteres (2 algarismos distintos seguidos de 3 letras diferentes, nessa ordem), usando as teclas 1, 2, 5, 7 e 0 (e suas letras). O número de possibilidades diferentes para cadastrar a senha é [imagem oficial pendente: teclado]',
            'alternatives' => ['A' => '11520.', 'B' => '14400.', 'C' => '18000.', 'D' => '312000.', 'E' => '390000.']],
        ['n' => 166, 'discipline' => 'Matemática', 'correct' => 'A', 'status' => 'ativa', 'content' => 'Conhecimentos numéricos', 'competency' => 'MT-C1', 'skill' => 'MT-H3', 'confidence' => 'alta', 'review' => false, 'page' => 28,
            'statement' => 'Enfeite com 2 unidades de X e 1 de Y. Loja I: X 3,00 / Y 1,00; Loja II: X 2,00 / Y 4,00. Comprando tudo na loja de menor valor total, o artesão efetuará a compra na loja',
            'alternatives' => ['A' => 'I, pois o valor é R$ 7,00.', 'B' => 'I, pois o valor é R$ 4,00.', 'C' => 'II, pois o valor é R$ 6,00.', 'D' => 'I, pois anuncia o componente com o menor preço.', 'E' => 'II, pois o componente X, que é o mais utilizado, tem menor preço.']],
        ['n' => 167, 'discipline' => 'Matemática', 'correct' => 'B', 'status' => 'ativa', 'content' => 'Conhecimentos numéricos', 'competency' => 'MT-C1', 'skill' => 'MT-H3', 'confidence' => 'alta', 'review' => false, 'page' => 28,
            'statement' => 'Maratona de 200 questões; conceitos por % de acerto (insatisfatório <50; regular 50–60; bom 60–75; muito bom 75–90; excelente 90–100). João acertou 75% e Felipe 30% a menos que João. Os conceitos de João e Felipe foram, respectivamente,',
            'alternatives' => ['A' => 'muito bom e bom.', 'B' => 'muito bom e regular.', 'C' => 'muito bom e insatisfatório.', 'D' => 'bom e regular.', 'E' => 'bom e insatisfatório.']],
        ['n' => 168, 'discipline' => 'Matemática', 'correct' => 'B', 'status' => 'ativa', 'content' => 'Conhecimentos algébricos', 'competency' => 'MT-C6', 'skill' => 'MT-H24', 'confidence' => 'media', 'review' => true, 'page' => 28,
            'statement' => 'Três grandezas I, II e III; gráficos relacionam I×II e II×III. O valor máximo assumido pela grandeza III, quando a grandeza I varia de 1 a 3, é [imagem oficial pendente: gráficos]',
            'alternatives' => ['A' => '1,0.', 'B' => '2,5.', 'C' => '3,0.', 'D' => '3,5.', 'E' => '4,0.']],
        ['n' => 169, 'discipline' => 'Matemática', 'correct' => 'A', 'status' => 'ativa', 'content' => 'Conhecimentos numéricos', 'competency' => 'MT-C1', 'skill' => 'MT-H2', 'confidence' => 'alta', 'review' => false, 'page' => 29,
            'statement' => 'Mensagem: 1ª etapa insere 3 figuras; em cada etapa copia e cola ao lado o que havia na etapa anterior, até a 20ª etapa. Qual foi o total de figuras na mensagem enviada?',
            'alternatives' => ['A' => '3 × 2¹⁹', 'B' => '3 × 2²⁰', 'C' => '3 × 2²¹', 'D' => '3 × 2²⁰ − 1', 'E' => '3 × 2²⁰ − 3']],
        ['n' => 170, 'discipline' => 'Matemática', 'correct' => 'D', 'status' => 'ativa', 'content' => 'Conhecimentos algébricos', 'competency' => 'MT-C5', 'skill' => 'MT-H21', 'confidence' => 'media', 'review' => true, 'page' => 29,
            'statement' => 'Casa de shows: custo R$34.350,00; 500 ingressos (R$130,00 inteira; R$65,00 meia, 60% previstos, mas meias superaram em 50% o previsto); bebidas/petiscos com 60% de lucro; lucro esperado R$17.000,00. Para alcançar o lucro, o gasto médio por pessoa com bebidas e petiscos, em real, deverá ser de',
            'alternatives' => ['A' => '19,50.', 'B' => '28,80.', 'C' => '34,00.', 'D' => '52,00.', 'E' => '68,70.']],
        ['n' => 171, 'discipline' => 'Matemática', 'correct' => 'D', 'status' => 'ativa', 'content' => 'Conhecimentos geométricos', 'competency' => 'MT-C2', 'skill' => 'MT-H7', 'confidence' => 'media', 'review' => true, 'page' => 29,
            'statement' => 'Trapézio retângulo PQRS afixado pelo lado PS a uma vareta e girado 360°. O sólido obtido foi um(a) [imagem oficial pendente: trapézio e vareta]',
            'alternatives' => ['A' => 'cone.', 'B' => 'cilindro.', 'C' => 'pirâmide.', 'D' => 'tronco de cone.', 'E' => 'tronco de pirâmide.']],
        ['n' => 172, 'discipline' => 'Matemática', 'correct' => 'D', 'status' => 'ativa', 'content' => 'Conhecimentos geométricos', 'competency' => 'MT-C2', 'skill' => 'MT-H8', 'confidence' => 'alta', 'review' => false, 'page' => 29,
            'statement' => 'Campo do Maracanã reduzido de 110 m × 75 m para 105 m × 68 m. Em quantos metros quadrados a área do campo foi reduzida?',
            'alternatives' => ['A' => '24', 'B' => '35', 'C' => '555', 'D' => '1110', 'E' => '1145']],
        ['n' => 173, 'discipline' => 'Matemática', 'correct' => 'C', 'status' => 'ativa', 'content' => 'Grandezas e medidas', 'competency' => 'MT-C3', 'skill' => 'MT-H12', 'confidence' => 'media', 'review' => true, 'page' => 30,
            'statement' => 'Piso 3 m × 6 m dividido por colunas cilíndricas (em reta paralela ao lado menor); vãos entre colunas e entre coluna e parede no máximo 15 cm. Lojas: I r=5/R$60; II r=10/R$70; III r=12/R$75; IV r=15/R$90; V r=20/R$120. Comprar no menor valor total. A compra será realizada na loja [imagem oficial pendente: figura e tabela]',
            'alternatives' => ['A' => 'I.', 'B' => 'II.', 'C' => 'III.', 'D' => 'IV.', 'E' => 'V.']],
        ['n' => 174, 'discipline' => 'Matemática', 'correct' => 'E', 'status' => 'ativa', 'content' => 'Grandezas e medidas', 'competency' => 'MT-C3', 'skill' => 'MT-H11', 'confidence' => 'alta', 'review' => false, 'page' => 30,
            'statement' => 'Maquete na escala 1:200; o vão aberto tem área real 1672 m². A medida da área do vão aberto na maquete, em centímetro quadrado, é',
            'alternatives' => ['A' => '4,18.', 'B' => '8,36.', 'C' => '41,80.', 'D' => '83,60.', 'E' => '418,00.']],
        ['n' => 175, 'discipline' => 'Matemática', 'correct' => 'A', 'status' => 'ativa', 'content' => 'Conhecimentos de estatística e probabilidade', 'competency' => 'MT-C6', 'skill' => 'MT-H26', 'confidence' => 'media', 'review' => true, 'page' => 30,
            'statement' => 'Gráfico de exportações e importações (bilhão de dólares); saldo = exportações − importações. Ordenar do maior para o menor os saldos S1 (jun/2009), S2 (jan/2010) e S3 (jun/2010). [imagem oficial pendente: gráfico]',
            'alternatives' => ['A' => 'S1, S3 e S2.', 'B' => 'S2, S1 e S3.', 'C' => 'S2, S3 e S1.', 'D' => 'S3, S1 e S2.', 'E' => 'S3, S2 e S1.']],
        ['n' => 176, 'discipline' => 'Matemática', 'correct' => 'D', 'status' => 'ativa', 'content' => 'Conhecimentos numéricos', 'competency' => 'MT-C1', 'skill' => 'MT-H1', 'confidence' => 'alta', 'review' => false, 'page' => 30,
            'statement' => 'O crescimento populacional de uma cidade foi de 135,25%. Qual é a representação decimal da taxa percentual desse crescimento populacional?',
            'alternatives' => ['A' => '13525,0', 'B' => '135,25', 'C' => '13,525', 'D' => '1,3525', 'E' => '0,13525']],
        ['n' => 177, 'discipline' => 'Matemática', 'correct' => 'B', 'status' => 'ativa', 'content' => 'Conhecimentos algébricos', 'competency' => 'MT-C5', 'skill' => 'MT-H21', 'confidence' => 'media', 'review' => true, 'page' => 31,
            'statement' => 'Galinheiro retangular L × C: nos lados L a tela custa R$20,00/m, nos outros dois R$15,00/m; gastar no máximo R$6.000,00 e maior área possível. Qual será a medida, em metro, do maior lado do galinheiro?',
            'alternatives' => ['A' => '85', 'B' => '100', 'C' => '175', 'D' => '200', 'E' => '350']],
        ['n' => 178, 'discipline' => 'Matemática', 'correct' => 'B', 'status' => 'ativa', 'content' => 'Conhecimentos numéricos', 'competency' => 'MT-C1', 'skill' => 'MT-H1', 'confidence' => 'media', 'review' => true, 'page' => 31,
            'statement' => 'Visor com seis números: I 4 1/2; II 4 1/2 (4½); III 10/45; IV 18/4; V 4,5; VI 4/5. As posições que representam a mesma quantidade são [imagem oficial pendente: visor]',
            'alternatives' => ['A' => 'I, II e IV.', 'B' => 'II, IV e V.', 'C' => 'II, III e V.', 'D' => 'III, V e VI.', 'E' => 'III, IV e VI.']],
        ['n' => 179, 'discipline' => 'Matemática', 'correct' => 'C', 'status' => 'ativa', 'content' => 'Conhecimentos algébricos', 'competency' => 'MT-C5', 'skill' => 'MT-H21', 'confidence' => 'media', 'review' => true, 'page' => 31,
            'statement' => 'Temperatura da caneca T(t) = a + 80·b^t (gráfico de 100 °C decaindo a 40 °C em 20 min). Os valores das constantes a e b são [imagem oficial pendente: gráfico]',
            'alternatives' => ['A' => 'a = 20; b = log(0,5)', 'B' => 'a = 100; b = 0,5', 'C' => 'a = 20; b = (0,5)^(1/10)', 'D' => 'a = 20; b = (40)^(1/10)/80', 'E' => 'a = 20; b = 40']],
        ['n' => 180, 'discipline' => 'Matemática', 'correct' => 'E', 'status' => 'ativa', 'content' => 'Conhecimentos geométricos', 'competency' => 'MT-C2', 'skill' => 'MT-H8', 'confidence' => 'media', 'review' => true, 'page' => 31,
            'statement' => 'Embalagem cilíndrica (raio 3 cm, altura 15 cm) será trocada por um cubo com capacidade igual a 80% da do cilindro (π ≈ 3). A medida da aresta da nova embalagem, em centímetro, deve ser',
            'alternatives' => ['A' => '6', 'B' => '18', 'C' => '6√6', 'D' => '6·∛6', 'E' => '3·∛12']],
    ],
];
